### PR TITLE
Jenkinsfile: abort previous build for the same job

### PR DESCRIPTION
**Pull request by pookimon**
Script will abort previous running build if a new build is in progress.
It checks running builds of current job and abort if there are some
ecxept the current one.
It will be helpful especially for Pull Requests builds to abort build
if PR was updated.

Signed-off-by: Dmytro Iurchuk <DIurchuk@luxoft.com>

### CODE REVIEW

**Comment by sashko** [comment]
fo the same PR you've meant?

**Comment by pookimon** [comment]
Excuse me?

**Comment by pookimon** [comment]
> fo the same PR you've meant?

yes

**Comment by pookimon** [comment]
It's an old solution which was srpead among meta layers, but I forgot to add the same to pelux-manifests

**Pull request merged**
