### PR TITLE
yocto2.groovy: add timestamper

### PR DESCRIPTION
**Pull request by pookimon**
Timestamper plugin call was added for most time consuming
pieces of pipeline to follow the proccess of building

Signed-off-by: Dmytro Iurchuk <DIurchuk@luxoft.com>

### CODE REVIEW

**Comment by martin-ejdestig** [comment]
Waited on build to finish to see how output looked but it failed. (I am guessing this is something added by a plugin?)

**Comment by sashko** [comment]
Looks good, but fix spelling in the commit message.

**Comment by martin-ejdestig** [comment]
Is it perhaps interesting to timestap the "repo init" stage as well? (Long, as in takes more than ~1 minute, task and involves external parties/networking that might slow down build so interesting to know what is going on.)

**Comment by pookimon** [comment]
> Is it perhaps interesting to timestap the "repo init" stage as well? (Long, as in takes more than ~1 minute, task and involves external parties/networking that might slow down build so interesting to know what is going on.)

Done

**Pull request merged**
