### PR TITLE
yocto.groovy: Run compatibility tests on every build

### PR DESCRIPTION
**Pull request by TSAnsari**
Signed-off-by: Tariq Ansari <tansari@luxoft.com>

### CODE REVIEW

**Comment by sashko** [comment]
on every build?

**Comment by TSAnsari** [comment]
@sashko Isn't this what we said in the daily standup, since weekly and nightly pipelines are not running properly due to global configs overriding the local pipeline configs in Jenkins, resulting in these checks not running. So we add it where it run even with global config.

**Comment by thenor** [comment]
@TSAnsari I don't know if that is what was said, but that might be one way to work around the issue.

**Comment by sashko** [comment]
I'm sorry, but I don't like the idea of running additional code we need to look very occasionally into on every single build.

**Pull request merged**
