### PR TITLE
Pelux 3.0 bump

### PR DESCRIPTION
**Pull request by thenor**

### CODE REVIEW

**Comment by thenor** [comment]
I would like to test this manually on at least one target so neptune-UI is still working as expected.

**Comment by thenor** [comment]
This is not building, so I will postpone this work until next week because this week there are more urgent tasks.

**Comment by fhajredini** [comment]
This PR is gonna be closed i assume?

**Comment by thenor** [comment]
@fhajredini I think Oleksandr may have done most of this work already, so yes.

**Comment by thenor** [comment]
We will do this work later. No need to keep this PR open.

**Pull request closed without merging**
