### PR TITLE
scripts: add mkefiWrap script

### PR DESCRIPTION
**Pull request by DunderRoffe**
Add script for speeding up the process of putting images on SD-cards and
USB-sticks.

Signed-off-by: Viktor Sjölind <viktor.sjolind@pelagicore.com>

### CODE REVIEW

**Comment by DunderRoffe** [comment]
Offline comments from @rpannek  and @erikboto suggests that the scripts should be moved to meta-pelux or meta-bistro. However, I forgot the reasoning could you refresh my memory?

**Comment by rpannek** [comment]
meta-bistro is a layer whith all kinds of software on top of meta-ivi, so it's more probabry to be used more often than the pelux-manifests, especially the manifests will be forked by each project so we can't update this script as easily. But now I'm not sure about the future role of meta-bistro, so meta-plux might be a good way too, or perhaps upstream it to poky and make the functionality part of mkefidisk.sh instead?

**Comment by erikboto** [comment]
When working you usually don't have the manifest git easily accessible since it is only used by repo, but meta-pelux would be easily accessible under sources/meta-pelux.

**Comment by DunderRoffe** [comment]
OK I will move the script to meta-pelux and update this PR accordingly.

**Comment by DunderRoffe** [comment]
Pending: https://github.com/Pelagicore/meta-pelux/pull/10

**Comment by erikboto** [comment]
Now merged in meta-pelux, closing this PR.

**Pull request closed without merging**
