### PR TITLE
Dockerfile: upgrade image to Ubuntu 18.04

### PR DESCRIPTION
**Pull request by sashko**
Upgraded Ubuntu image to 18.04 and sorted the packages to be installed
by alphabet.

Signed-off-by: Oleksandr Kravchuk <oleksandr.kravchuk@pelagicore.com>

### CODE REVIEW

**Comment by martin-ejdestig** [comment]
Maybe hold on with this until we can verify that it works with the CI/CD?

**Comment by thenor** [comment]
Regarding the possible issue I mentioned with poky (that perhaps they can't be run on 18.04 due to the default version of a library), it seems Fisnik has run the tests on 18.04 and didn't see the same issue I saw, so hopefully it's not an issue with 18.04 in general.

**Comment by sashko** [comment]
> Regarding the possible issue I mentioned with poky tests (that perhaps they can't be run on 18.04 due to the default version of a library), it seems Fisnik has run the tests on 18.04 and didn't see the same issue I saw, so hopefully it's not an issue with 18.04 in general.

Could you please elaborate here for the record?

**Comment by thenor** [comment]
This is the error I get if I run it manually on one of our build servers: `runqemu - ERROR - Failed to run qemu: /home/thenor/development/pelux/build/tmp/work/x86_64-linux/qemu-helper-native/1.0-r1/recipe-sysroot-native/usr/bin/qemu-system-x86_64: error while loading shared libraries: libfdt.so.1: cannot open shared object file: No such file or directory`
I searched for this error, but couldn't find anyone else that had reported this library specifically, but some had reported similar issues and for them it was just the version of that library which was not aligned with the poky version. 
When running this through Jenkins we use a Dockerfile with Ubuntu 16.04 and since the default lifdt version differs between 16.04 and 18.04 I thought perhaps that might be the reason for the error that I saw, until Fisnik mentioned that he had run it on the new servers and not seen the same issue as I saw. So now I don't know anymore. :P

**Comment by sashko** [comment]
@thenor just bumped into this issue on my machine; installing correct package fixed it: docker filed tried to install `libfdt1.2-dev`, while `Ubuntu 18.04` contains `libfdt-dev` v1.4.

**Comment by thenor** [comment]
So should we reopen this merge request? @sashko

**Comment by sashko** [comment]
@thenor I am testing it on Jenkins atm; once it is stable, I'll do it.

**Comment by martin-ejdestig** [comment]
Happened to notice that we are still on 16.04 today when looking at a build problem with @JEderonn when using Docker locally. Had forgotten that this was not merged. TIme to give it another try?

**Comment by sashko** [comment]
> Happened to notice that we are still on 16.04 today when looking at a build problem with @JEderonn when using Docker locally. Had forgotten that this was not merged. TIme to give it another try?

smoke tests still fail :crying_cat_face:

**Comment by martin-ejdestig** [comment]
Hum, I do not understand.

> installing correct package fixed it: docker filed tried to install libfdt1.2-dev, while Ubuntu 18.04 contains libfdt-dev v1.4.

That fixed the issue you were seeing?

Or what is the issue currently? Ubuntu 18.04 should be supported in thud (that we have on master currently), I think. See https://git.yoctoproject.org/cgit/cgit.cgi/meta-yocto/tree/meta-poky/conf/distro/poky.conf?h=thud#n70 . If something is not working as it should in Yocto with 18.04 should at least file a bug somewhere? If it is something more on our end, what is it and can we fix it? :)

**Comment by sashko** [comment]
> Hum, I do not understand.
> 
> > installing correct package fixed it: docker filed tried to install libfdt1.2-dev, while Ubuntu 18.04 contains libfdt-dev v1.4.
> 
> That fixed the issue you were seeing?

https://github.com/sashko/pelux-manifests/commit/f802a4881d4b2a553f3a941f6c27e93c599ad62a#diff-3254677a7917c6c01f55212f86c57fbfL33

It has been a while though. Perhaps it's time to try it out again.

**Comment by martin-ejdestig** [comment]
So what is the error then?

**Comment by sashko** [comment]
> So what is the error then?

I don't have it on a top of my head and would need to re-run the job to get the exact error, but it was something to do with setting up tun interfaces for the smoke tests.

**Comment by JEderonn** [comment]
> Happened to notice that we are still on 16.04 today when looking at a build problem with @JEderonn when using Docker locally. Had forgotten that this was not merged. TIme to give it another try?

I get sporadic errors when running
```
docker exec pelux-build bash -c "/docker/build-in-docker.sh -v rpi-qtauto -i core-image-pelux-qtauto-neptune-dev -b master"
```
like for example:
```
| fsfeatures.o: file not recognized: File truncated
| collect2: error: ld returned 1 exit status
| Makefile:465: recipe for target 'btrfs' failed
| make: *** [btrfs] Error 1
| make: *** Waiting for unfinished jobs....
| fsfeatures.o: file not recognized: File truncated
| collect2: error: ld returned 1 exit status
| Makefile:482: recipe for target 'mkfs.btrfs' failed
| make: *** [mkfs.btrfs] Error 1
| fsfeatures.o: file not recognized: File truncated
| collect2: error: ld returned 1 exit status
| Makefile:458: recipe for target 'btrfs-map-logical' failed
| make: *** [btrfs-map-logical] Error 1
| ERROR: oe_runmake failed
| WARNING: exit code 1 from a shell command.
| ERROR: Function failed: do_compile (log file is located at /docker/build/build/tmp/work/x86_64-linux/btrfs-tools-native/4.17.1-r0/temp/log.do_compile.325)
NOTE: recipe btrfs-tools-native-4.17.1-r0: task do_compile: Failed
ERROR: Task (virtual:native:/docker/build/build/../sources/poky/meta/recipes-devtools/btrfs-tools/btrfs-tools_4.17.1.bb:do_compile) failed with exit code '1'
```

Another time a got a failure when building qtdeclarative, it complained about an empty object-file at linking stage.

I not been able to finish the PELUX build using Docker on Ubuntu 18.04. The Dockerfile in pelux-manifests still states
`FROM ubuntu:16.04
`

**Pull request closed without merging**
