### PR TITLE
Topic/qt5.11

### PR DESCRIPTION
**Pull request by Gagi2k**

### CODE REVIEW

**Comment by Gagi2k** [comment]
I probably need to update this again once the commit meta-pelux landed

**Comment by thenor** [comment]
I have merged the meta-pelux change into the topic branch in that repo now.

**Comment by Gagi2k** [comment]
i updated the commit to contain the new version of meta-pelux topic/qt5.11

**Comment by thenor** [comment]
At least one of the build failures was a known docker issue we have.

**Comment by thenor** [comment]
The intel and rpi builds seem to have failed, but are still marked as a success. Not sure why.
The qtauto builds failed, but I think one would need to run it manually since Jenkins removes the logs during clean-up.

**Pull request merged**
