### PR TITLE
Fix intermittent IO errors in CI/CD by moving Yocto build dir to bind mount from overlay2 fs

### PR DESCRIPTION
**Pull request by martin-ejdestig**
Have run a couple of full builds (intel, intel-qtauto, rpi and rpi-qtauto) on stockholm, reykjavik, kyiv and helsinki with this and all intermittent build errors are gone. Did not manage to pass a single full build on any of these nodes before.

### CODE REVIEW

**Comment by rpannek** [comment]
You're removing `checkout scm`, how do you checkout the pelux-manifests git repo during a nightly build which is not triggered by a different job like meta-pelux?

**Comment by martin-ejdestig** [comment]
@rpannek It is already done in JenkinsFile that then imports ci-scripts/yocto.groovy. I wrote a sentence about that in the commit message but perhaps I should clarify a bit.

**Comment by thenor** [comment]
The title of this pull request is only reflecting one of the commits. I guess the total change is larger than just that one commit. I would prefer a more explanatory PR title.

**Comment by martin-ejdestig** [comment]
The commits prior to the last one are cleanups (that make the final commit "simpler") or fixes (required for final commit to work "more correctly"). Not sure what to put in the title. Do not want to squash commits (small commits, that makes sense on their own, ftw!).

**Comment by rpannek** [comment]
I read the commit message but didn't quite get that from it, thanks for clearifying.

**Pull request merged**
