### PR TITLE
pelux.xml: Add meta-swupdate

### PR DESCRIPTION
**Pull request by FlorentRevest**
In order to integrate swupdate to PELUX, this PR downloads meta-pelux into the sources/ directory.

This PR is written for pyro. If https://github.com/Pelagicore/pelux-manifests/pull/112 is merged before, I will update the current commit hash and branch label to point to the rocko branch of meta-swupdate.

### CODE REVIEW

**Comment by GordanM** [comment]
AFAIK, new features should be developed against rocko (master) but I guess @tobsan and @thenor could give you more input on that, I might be mistaken. Unfortunately, there are some problems with the docker containers or the slaves in our CI system so the tests are failing.

**Comment by thenor** [comment]
@FlorentRevest We have been having issues on the pelux-manifests CI and that is the reason why the rocko update is not on master yet. Tobias reverted a change that seemed to have introduced the issue, but it didn't solve it completely. I guess nothing is stopping other commits until the "bump to rocko" is merged, but just so you know the builds can fail for seemingly no reason.

**Comment by tobsan** [comment]
@FlorentRevest can you rebase this on top of master and target rocko instead, now that it has been merged? Thanks!

**Comment by tobsan** [comment]
Ehm...by target I mean yocto target, not branch! We still want it on master, but master currently targets rocko :D

**Comment by FlorentRevest** [comment]
tobsan: yep, I did it tonight and compiled while I was sleeping. I'm gonna check the results and send a PR once I'll be back home !

**Comment by FlorentRevest** [comment]
There you go!
https://github.com/Pelagicore/meta-pelux/pull/89 still applies cleanly and has been tested manually to not break anything.
https://github.com/Pelagicore/pelux.io/pull/61 can then be merged as well.

We can wait for the CI to finish but since it probably already passed the repo commands, this should be ok.

**Pull request merged**
